# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  functional_web_test_suite:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:  
        working-directory: web

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: BrowserStack Action
        uses: 'browserstack/github-actions@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Percy
        run: npm install @percy/cli
         
      - name: Build with Maven
        env: 
          PERCY_TOKEN: ${{ secrets.WEB_PERCY_TOKEN }}
          BROWSERSTACK_CONFIG_FILE: src/test/resources/conf/capabilities/browserstack-parallel.yml
        run: npx percy exec -- mvn clean test -P bstack-parallel

  functional_app_test_suite:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:  
        working-directory: app

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: BrowserStack Action
        uses: 'browserstack/github-actions@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Percy
        run: npm install @percy/cli
         
      - name: Build with Maven
        env: 
          PERCY_TOKEN: ${{ secrets.APP_PERCY_TOKEN }}
          BROWSERSTACK_CONFIG_FILE: src/test/resources/conf/capabilities/browserstack-parallel.yml
        run: npx percy app:exec -- mvn clean test -P bstack-parallel